name: 彩票推荐和开奖通知

on:
  schedule:
    # 每天上午9点运行推荐号码任务
    - cron: '0 1 * * *'  # UTC时间1点，对应北京时间9点
    # 每天晚上10点运行开奖查询任务
    - cron: '14 14 * * *'  # UTC时间14点14分，对应北京时间22点14分
  # 添加手动触发
  workflow_dispatch:
    inputs:
      action_type:
        description: '选择要执行的操作'
        required: true
        default: 'recommend'
        type: choice
        options:
          - recommend
          - check

jobs:
  lottery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv
          
      - name: 设置环境变量
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.LOTTERY_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: |
          echo "EMAIL_USER=$EMAIL_USER" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=$EMAIL_PASSWORD" >> $GITHUB_ENV
          echo "RECIPIENT_EMAIL=$RECIPIENT_EMAIL" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME" >> $GITHUB_ENV
          
      - name: 检查是否为周五
        id: check_friday
        run: |
          if [ "$(date +%u)" = "5" ]; then
            echo "is_friday=true" >> $GITHUB_OUTPUT
          else
            echo "is_friday=false" >> $GITHUB_OUTPUT
          fi
          
      - name: 运行彩票脚本
        if: steps.check_friday.outputs.is_friday != 'true'
        run: |
          if [ "${{ github.event.schedule }}" == "0 1 * * *" ] || [ "${{ github.event.inputs.action_type }}" == "recommend" ]; then
            python scripts/lottery_recommendation.py
          else
            python scripts/lottery_check.py
          fi 